// <auto-generated />
using AsyncInnAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AsyncInnAPI.Migrations
{
    [DbContext(typeof(AsyncInnDbContext))]
    partial class AsyncInnDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AsyncInnAPI.Models.Amenity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Hair Dryer"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Water"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Extra Pillows"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Extra Blankets"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Wine"
                        });
                });

            modelBuilder.Entity("AsyncInnAPI.Models.Hotel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            City = "One",
                            Name = "Hotel One",
                            Phone = "111-111-1111",
                            State = "Number",
                            StreetAddress = "1111 One Street"
                        },
                        new
                        {
                            ID = 2,
                            City = "Two",
                            Name = "Hotel Two",
                            Phone = "222-222-2222",
                            State = "Number",
                            StreetAddress = "2222 Two Street"
                        },
                        new
                        {
                            ID = 3,
                            City = "Three",
                            Name = "Hotel Three",
                            Phone = "333-333-3333",
                            State = "Number",
                            StreetAddress = "3333 Three Street"
                        },
                        new
                        {
                            ID = 4,
                            City = "Four",
                            Name = "Hotel Four",
                            Phone = "206-681-4444",
                            State = "Number",
                            StreetAddress = "4444 Four Street"
                        },
                        new
                        {
                            ID = 5,
                            City = "Five",
                            Name = "Hotel Five",
                            Phone = "555-555-5555",
                            State = "Number",
                            StreetAddress = "5555 Five Street"
                        });
                });

            modelBuilder.Entity("AsyncInnAPI.Models.Room", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Layout")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Layout = 1,
                            Name = "Room One"
                        },
                        new
                        {
                            ID = 2,
                            Layout = 0,
                            Name = "Room Two"
                        },
                        new
                        {
                            ID = 3,
                            Layout = 2,
                            Name = "Room Three"
                        },
                        new
                        {
                            ID = 4,
                            Layout = 0,
                            Name = "Room Four"
                        },
                        new
                        {
                            ID = 5,
                            Layout = 1,
                            Name = "Room Five"
                        },
                        new
                        {
                            ID = 6,
                            Layout = 2,
                            Name = "Room Six"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
